/**
 * Generated by @haozeke/capnpc-ts. Do not hand-edit.
 *
 * Source schema: schema/rpc-threeparty.capnp
 * CodeGeneratorRequest: nodes=7, requestedFiles=1
 * File id: 0xd94d1d3f0d9f8a11 (emitted 6 nested nodes)
 *
 * Enums are const maps (Bun strip-safe). UInt64/Int64 use getU64/bigint.
 */

import type { Ptr } from "@haozeke/capnp";

export const __capnpcTsMeta = {
  schemaPath: "schema/rpc-threeparty.capnp",
  nodeCount: 7,
  requestedFileCount: 1,
  fileId: 0xd94d1d3f0d9f8a11n,
  emittedNodes: 6,
} as const;

/** Struct schema/rpc-threeparty.capnp:VatId. */
export const VAT_ID_DWORDS = 1;
export const VAT_ID_PWORDS = 1;
export const VatId_dataWordCount = 1;
export const VatId_pointerCount = 1;

export function VatId_getHost(ptr: Ptr): string {
  return ptr.getText(0);
}

export function VatId_getPort(ptr: Ptr, dflt = 0): number {
  return ptr.getU16(0, dflt);
}

/** Struct schema/rpc-threeparty.capnp:ProvisionId. */
export const PROVISION_ID_DWORDS = 1;
export const PROVISION_ID_PWORDS = 0;
export const ProvisionId_dataWordCount = 1;
export const ProvisionId_pointerCount = 0;

export function ProvisionId_getNonce(ptr: Ptr, dflt: bigint = 0n): bigint {
  return ptr.getU64(0, dflt);
}

/** Struct schema/rpc-threeparty.capnp:RecipientId. */
export const RECIPIENT_ID_DWORDS = 1;
export const RECIPIENT_ID_PWORDS = 1;
export const RecipientId_dataWordCount = 1;
export const RecipientId_pointerCount = 1;

export function RecipientId_getVat(ptr: Ptr): Ptr {
  return ptr.getP(0);
}

export function RecipientId_getNonce(ptr: Ptr, dflt: bigint = 0n): bigint {
  return ptr.getU64(0, dflt);
}

/** Struct schema/rpc-threeparty.capnp:ThirdPartyCapId. */
export const THIRD_PARTY_CAP_ID_DWORDS = 1;
export const THIRD_PARTY_CAP_ID_PWORDS = 1;
export const ThirdPartyCapId_dataWordCount = 1;
export const ThirdPartyCapId_pointerCount = 1;

export function ThirdPartyCapId_getVat(ptr: Ptr): Ptr {
  return ptr.getP(0);
}

export function ThirdPartyCapId_getNonce(ptr: Ptr, dflt: bigint = 0n): bigint {
  return ptr.getU64(0, dflt);
}

/** Struct schema/rpc-threeparty.capnp:JoinKeyPart. */
export const JOIN_KEY_PART_DWORDS = 1;
export const JOIN_KEY_PART_PWORDS = 0;
export const JoinKeyPart_dataWordCount = 1;
export const JoinKeyPart_pointerCount = 0;

export function JoinKeyPart_getJoinId(ptr: Ptr, dflt = 0): number {
  return ptr.getU32(0, dflt);
}

export function JoinKeyPart_getPartCount(ptr: Ptr, dflt = 0): number {
  return ptr.getU16(4, dflt);
}

export function JoinKeyPart_getPartNum(ptr: Ptr, dflt = 0): number {
  return ptr.getU16(6, dflt);
}

/** Struct schema/rpc-threeparty.capnp:JoinResult. */
export const JOIN_RESULT_DWORDS = 1;
export const JOIN_RESULT_PWORDS = 1;
export const JoinResult_dataWordCount = 1;
export const JoinResult_pointerCount = 1;

export function JoinResult_getJoinId(ptr: Ptr, dflt = 0): number {
  return ptr.getU32(0, dflt);
}

export function JoinResult_getSucceeded(ptr: Ptr, dflt = false): boolean {
  return ptr.getBool(32, dflt);
}

export function JoinResult_getCap(ptr: Ptr): Ptr {
  return ptr.getP(0);
}
