/**
 * Generated by @haozeke/capnpc-ts. Do not hand-edit.
 *
 * Source schema: rpc-twoparty.capnp
 * CodeGeneratorRequest: nodes=10, requestedFiles=1
 * File id: 0xa184c7885cdaf2a1 (emitted 7 nested nodes)
 *
 * Enums are const maps (Bun strip-safe). UInt64/Int64 use getU64/bigint.
 */

import type { Ptr } from "@haozeke/capnp";

export const __capnpcTsMeta = {
  schemaPath: "rpc-twoparty.capnp",
  nodeCount: 10,
  requestedFileCount: 1,
  fileId: 0xa184c7885cdaf2a1n,
  emittedNodes: 7,
} as const;

/** Enum rpc-twoparty.capnp:Side (const map; no TS enum keyword). */
export const Side = {
  server: 0,
  client: 1,
} as const;
export type Side = (typeof Side)[keyof typeof Side];

/** Struct rpc-twoparty.capnp:VatId. */
export const VAT_ID_DWORDS = 1;
export const VAT_ID_PWORDS = 0;
export const VatId_dataWordCount = 1;
export const VatId_pointerCount = 0;

export function VatId_getSide(ptr: Ptr, dflt = 0): number {
  return ptr.getU16(0, dflt);
}

/** Struct rpc-twoparty.capnp:ProvisionId. */
export const PROVISION_ID_DWORDS = 1;
export const PROVISION_ID_PWORDS = 0;
export const ProvisionId_dataWordCount = 1;
export const ProvisionId_pointerCount = 0;

export function ProvisionId_getJoinId(ptr: Ptr, dflt = 0): number {
  return ptr.getU32(0, dflt);
}

/** Struct rpc-twoparty.capnp:RecipientId. */
export const RECIPIENT_ID_DWORDS = 0;
export const RECIPIENT_ID_PWORDS = 0;
export const RecipientId_dataWordCount = 0;
export const RecipientId_pointerCount = 0;

/** Struct rpc-twoparty.capnp:ThirdPartyCapId. */
export const THIRD_PARTY_CAP_ID_DWORDS = 0;
export const THIRD_PARTY_CAP_ID_PWORDS = 0;
export const ThirdPartyCapId_dataWordCount = 0;
export const ThirdPartyCapId_pointerCount = 0;

/** Struct rpc-twoparty.capnp:JoinKeyPart. */
export const JOIN_KEY_PART_DWORDS = 1;
export const JOIN_KEY_PART_PWORDS = 0;
export const JoinKeyPart_dataWordCount = 1;
export const JoinKeyPart_pointerCount = 0;

export function JoinKeyPart_getJoinId(ptr: Ptr, dflt = 0): number {
  return ptr.getU32(0, dflt);
}

export function JoinKeyPart_getPartCount(ptr: Ptr, dflt = 0): number {
  return ptr.getU16(4, dflt);
}

export function JoinKeyPart_getPartNum(ptr: Ptr, dflt = 0): number {
  return ptr.getU16(6, dflt);
}

/** Struct rpc-twoparty.capnp:JoinResult. */
export const JOIN_RESULT_DWORDS = 1;
export const JOIN_RESULT_PWORDS = 1;
export const JoinResult_dataWordCount = 1;
export const JoinResult_pointerCount = 1;

export function JoinResult_getJoinId(ptr: Ptr, dflt = 0): number {
  return ptr.getU32(0, dflt);
}

export function JoinResult_getSucceeded(ptr: Ptr, dflt = false): boolean {
  return ptr.getBool(32, dflt);
}

export function JoinResult_getCap(ptr: Ptr): Ptr {
  return ptr.getP(0);
}
