/**
 * Generated by @haozeke/capnpc-ts. Do not hand-edit.
 *
 * Source schema: rpc.capnp
 * CodeGeneratorRequest: nodes=24, requestedFiles=1
 * File id: 0xb312981b2552a250 (emitted 21 nested nodes)
 *
 * Enums are const maps (Bun strip-safe). UInt64/Int64 use getU64/bigint.
 */

import type { Ptr } from "@haozeke/capnp";

export const __capnpcTsMeta = {
  schemaPath: "rpc.capnp",
  nodeCount: 24,
  requestedFileCount: 1,
  fileId: 0xb312981b2552a250n,
  emittedNodes: 21,
} as const;

/** Enum rpc.capnp:Exception.Type (const map; no TS enum keyword). */
export const Exception_Type = {
  failed: 0,
  overloaded: 1,
  disconnected: 2,
  unimplemented: 3,
} as const;
export type Exception_Type = (typeof Exception_Type)[keyof typeof Exception_Type];

/** Struct rpc.capnp:Message. */
export const MESSAGE_DWORDS = 1;
export const MESSAGE_PWORDS = 1;
export const Message_dataWordCount = 1;
export const Message_pointerCount = 1;
/** Union discriminant byte offset (u16). */
export const Message_discriminantOffset = 0;
export function Message_which(ptr: Ptr): number {
  return ptr.getU16(0);
}
export const Message = {
  unimplemented: 0,
  abort: 1,
  call: 2,
  return: 3,
  finish: 4,
  resolve: 5,
  release: 6,
  obsoleteSave: 7,
  bootstrap: 8,
  obsoleteDelete: 9,
  provide: 10,
  accept: 11,
  join: 12,
  disembargo: 13,
} as const;
export type Message = (typeof Message)[keyof typeof Message];

export function Message_getUnimplemented(ptr: Ptr): Ptr {
  return ptr.getP(0);
}

export function Message_getAbort(ptr: Ptr): Ptr {
  return ptr.getP(0);
}

export function Message_getCall(ptr: Ptr): Ptr {
  return ptr.getP(0);
}

export function Message_getReturn(ptr: Ptr): Ptr {
  return ptr.getP(0);
}

export function Message_getFinish(ptr: Ptr): Ptr {
  return ptr.getP(0);
}

export function Message_getResolve(ptr: Ptr): Ptr {
  return ptr.getP(0);
}

export function Message_getRelease(ptr: Ptr): Ptr {
  return ptr.getP(0);
}

export function Message_getObsoleteSave(ptr: Ptr): Ptr {
  return ptr.getP(0);
}

export function Message_getBootstrap(ptr: Ptr): Ptr {
  return ptr.getP(0);
}

export function Message_getObsoleteDelete(ptr: Ptr): Ptr {
  return ptr.getP(0);
}

export function Message_getProvide(ptr: Ptr): Ptr {
  return ptr.getP(0);
}

export function Message_getAccept(ptr: Ptr): Ptr {
  return ptr.getP(0);
}

export function Message_getJoin(ptr: Ptr): Ptr {
  return ptr.getP(0);
}

export function Message_getDisembargo(ptr: Ptr): Ptr {
  return ptr.getP(0);
}

/** Struct rpc.capnp:Exception. */
export const EXCEPTION_DWORDS = 1;
export const EXCEPTION_PWORDS = 2;
export const Exception_dataWordCount = 1;
export const Exception_pointerCount = 2;

export function Exception_getReason(ptr: Ptr): string {
  return ptr.getText(0);
}

export function Exception_getObsoleteIsCallersFault(ptr: Ptr, dflt = false): boolean {
  return ptr.getBool(0, dflt);
}

export function Exception_getObsoleteDurability(ptr: Ptr, dflt = 0): number {
  return ptr.getU16(2, dflt);
}

export function Exception_getType(ptr: Ptr, dflt = 0): number {
  return ptr.getU16(4, dflt);
}

export function Exception_getTrace(ptr: Ptr): string {
  return ptr.getText(1);
}

/** Struct rpc.capnp:Call. */
export const CALL_DWORDS = 3;
export const CALL_PWORDS = 3;
export const Call_dataWordCount = 3;
export const Call_pointerCount = 3;

export function Call_getQuestionId(ptr: Ptr, dflt = 0): number {
  return ptr.getU32(0, dflt);
}

export function Call_getTarget(ptr: Ptr): Ptr {
  return ptr.getP(0);
}

export function Call_getInterfaceId(ptr: Ptr, dflt: bigint = 0n): bigint {
  return ptr.getU64(8, dflt);
}

export function Call_getMethodId(ptr: Ptr, dflt = 0): number {
  return ptr.getU16(4, dflt);
}

export function Call_getParams(ptr: Ptr): Ptr {
  return ptr.getP(1);
}

/** Group field `sendResultsTo` — same wire Ptr as parent; see group node helpers. */
export function Call_getSendResultsTo(ptr: Ptr): Ptr {
  return ptr;
}

export function Call_getAllowThirdPartyTailCall(ptr: Ptr, dflt = false): boolean {
  return ptr.getBool(128, dflt);
}

export function Call_getNoPromisePipelining(ptr: Ptr, dflt = false): boolean {
  return ptr.getBool(129, dflt);
}

export function Call_getOnlyPromisePipeline(ptr: Ptr, dflt = false): boolean {
  return ptr.getBool(130, dflt);
}

/** Struct rpc.capnp:Return. */
export const RETURN_DWORDS = 2;
export const RETURN_PWORDS = 1;
export const Return_dataWordCount = 2;
export const Return_pointerCount = 1;
/** Union discriminant byte offset (u16). */
export const Return_discriminantOffset = 6;
export function Return_which(ptr: Ptr): number {
  return ptr.getU16(6);
}
export const Return = {
  results: 0,
  exception: 1,
  canceled: 2,
  resultsSentElsewhere: 3,
  takeFromOtherQuestion: 4,
  acceptFromThirdParty: 5,
} as const;
export type Return = (typeof Return)[keyof typeof Return];

export function Return_getAnswerId(ptr: Ptr, dflt = 0): number {
  return ptr.getU32(0, dflt);
}

export function Return_getReleaseParamCaps(ptr: Ptr, dflt = true): boolean {
  return ptr.getBool(32, dflt);
}

export function Return_getResults(ptr: Ptr): Ptr {
  return ptr.getP(0);
}

export function Return_getException(ptr: Ptr): Ptr {
  return ptr.getP(0);
}

export function Return_getTakeFromOtherQuestion(ptr: Ptr, dflt = 0): number {
  return ptr.getU32(8, dflt);
}

export function Return_getAcceptFromThirdParty(ptr: Ptr): Ptr {
  return ptr.getP(0);
}

export function Return_getNoFinishNeeded(ptr: Ptr, dflt = false): boolean {
  return ptr.getBool(33, dflt);
}

/** Struct rpc.capnp:Finish. */
export const FINISH_DWORDS = 1;
export const FINISH_PWORDS = 0;
export const Finish_dataWordCount = 1;
export const Finish_pointerCount = 0;

export function Finish_getQuestionId(ptr: Ptr, dflt = 0): number {
  return ptr.getU32(0, dflt);
}

export function Finish_getReleaseResultCaps(ptr: Ptr, dflt = true): boolean {
  return ptr.getBool(32, dflt);
}

export function Finish_getRequireEarlyCancellationWorkaround(ptr: Ptr, dflt = true): boolean {
  return ptr.getBool(33, dflt);
}

/** Struct rpc.capnp:Resolve. */
export const RESOLVE_DWORDS = 1;
export const RESOLVE_PWORDS = 1;
export const Resolve_dataWordCount = 1;
export const Resolve_pointerCount = 1;
/** Union discriminant byte offset (u16). */
export const Resolve_discriminantOffset = 4;
export function Resolve_which(ptr: Ptr): number {
  return ptr.getU16(4);
}
export const Resolve = {
  cap: 0,
  exception: 1,
} as const;
export type Resolve = (typeof Resolve)[keyof typeof Resolve];

export function Resolve_getPromiseId(ptr: Ptr, dflt = 0): number {
  return ptr.getU32(0, dflt);
}

export function Resolve_getCap(ptr: Ptr): Ptr {
  return ptr.getP(0);
}

export function Resolve_getException(ptr: Ptr): Ptr {
  return ptr.getP(0);
}

/** Struct rpc.capnp:Release. */
export const RELEASE_DWORDS = 1;
export const RELEASE_PWORDS = 0;
export const Release_dataWordCount = 1;
export const Release_pointerCount = 0;

export function Release_getId(ptr: Ptr, dflt = 0): number {
  return ptr.getU32(0, dflt);
}

export function Release_getReferenceCount(ptr: Ptr, dflt = 0): number {
  return ptr.getU32(4, dflt);
}

/** Struct rpc.capnp:Bootstrap. */
export const BOOTSTRAP_DWORDS = 1;
export const BOOTSTRAP_PWORDS = 1;
export const Bootstrap_dataWordCount = 1;
export const Bootstrap_pointerCount = 1;

export function Bootstrap_getQuestionId(ptr: Ptr, dflt = 0): number {
  return ptr.getU32(0, dflt);
}

export function Bootstrap_getDeprecatedObjectId(ptr: Ptr): Ptr {
  return ptr.getP(0);
}

/** Struct rpc.capnp:Provide. */
export const PROVIDE_DWORDS = 1;
export const PROVIDE_PWORDS = 2;
export const Provide_dataWordCount = 1;
export const Provide_pointerCount = 2;

export function Provide_getQuestionId(ptr: Ptr, dflt = 0): number {
  return ptr.getU32(0, dflt);
}

export function Provide_getTarget(ptr: Ptr): Ptr {
  return ptr.getP(0);
}

export function Provide_getRecipient(ptr: Ptr): Ptr {
  return ptr.getP(1);
}

/** Struct rpc.capnp:Accept. */
export const ACCEPT_DWORDS = 1;
export const ACCEPT_PWORDS = 1;
export const Accept_dataWordCount = 1;
export const Accept_pointerCount = 1;

export function Accept_getQuestionId(ptr: Ptr, dflt = 0): number {
  return ptr.getU32(0, dflt);
}

export function Accept_getProvision(ptr: Ptr): Ptr {
  return ptr.getP(0);
}

export function Accept_getEmbargo(ptr: Ptr, dflt = false): boolean {
  return ptr.getBool(32, dflt);
}

/** Struct rpc.capnp:Join. */
export const JOIN_DWORDS = 1;
export const JOIN_PWORDS = 2;
export const Join_dataWordCount = 1;
export const Join_pointerCount = 2;

export function Join_getQuestionId(ptr: Ptr, dflt = 0): number {
  return ptr.getU32(0, dflt);
}

export function Join_getTarget(ptr: Ptr): Ptr {
  return ptr.getP(0);
}

export function Join_getKeyPart(ptr: Ptr): Ptr {
  return ptr.getP(1);
}

/** Struct rpc.capnp:Disembargo. */
export const DISEMBARGO_DWORDS = 1;
export const DISEMBARGO_PWORDS = 1;
export const Disembargo_dataWordCount = 1;
export const Disembargo_pointerCount = 1;

export function Disembargo_getTarget(ptr: Ptr): Ptr {
  return ptr.getP(0);
}

/** Group field `context` — same wire Ptr as parent; see group node helpers. */
export function Disembargo_getContext(ptr: Ptr): Ptr {
  return ptr;
}

/** Struct rpc.capnp:Call.sendResultsTo (group / union overlay). */
export const CALL_SEND_RESULTS_TO_DWORDS = 3;
export const CALL_SEND_RESULTS_TO_PWORDS = 3;
export const Call_sendResultsTo_dataWordCount = 3;
export const Call_sendResultsTo_pointerCount = 3;
/** Union discriminant byte offset (u16). */
export const Call_sendResultsTo_discriminantOffset = 6;
export function Call_sendResultsTo_which(ptr: Ptr): number {
  return ptr.getU16(6);
}
export const Call_sendResultsTo = {
  caller: 0,
  yourself: 1,
  thirdParty: 2,
} as const;
export type Call_sendResultsTo = (typeof Call_sendResultsTo)[keyof typeof Call_sendResultsTo];

export function Call_sendResultsTo_getThirdParty(ptr: Ptr): Ptr {
  return ptr.getP(2);
}

/** Struct rpc.capnp:MessageTarget. */
export const MESSAGE_TARGET_DWORDS = 1;
export const MESSAGE_TARGET_PWORDS = 1;
export const MessageTarget_dataWordCount = 1;
export const MessageTarget_pointerCount = 1;
/** Union discriminant byte offset (u16). */
export const MessageTarget_discriminantOffset = 4;
export function MessageTarget_which(ptr: Ptr): number {
  return ptr.getU16(4);
}
export const MessageTarget = {
  importedCap: 0,
  promisedAnswer: 1,
} as const;
export type MessageTarget = (typeof MessageTarget)[keyof typeof MessageTarget];

export function MessageTarget_getImportedCap(ptr: Ptr, dflt = 0): number {
  return ptr.getU32(0, dflt);
}

export function MessageTarget_getPromisedAnswer(ptr: Ptr): Ptr {
  return ptr.getP(0);
}

/** Struct rpc.capnp:Payload. */
export const PAYLOAD_DWORDS = 0;
export const PAYLOAD_PWORDS = 2;
export const Payload_dataWordCount = 0;
export const Payload_pointerCount = 2;

export function Payload_getContent(ptr: Ptr): Ptr {
  return ptr.getP(0);
}

export function Payload_getCapTable(ptr: Ptr): Ptr {
  return ptr.getP(1);
}

export function Payload_getCapTableLen(ptr: Ptr): number {
  return ptr.getP(1).listLen();
}

export function Payload_getCapTableAt(ptr: Ptr, index: number): Ptr {
  return ptr.getP(1).listGetP(index);
}

/** Struct rpc.capnp:PromisedAnswer. */
export const PROMISED_ANSWER_DWORDS = 1;
export const PROMISED_ANSWER_PWORDS = 1;
export const PromisedAnswer_dataWordCount = 1;
export const PromisedAnswer_pointerCount = 1;

export function PromisedAnswer_getQuestionId(ptr: Ptr, dflt = 0): number {
  return ptr.getU32(0, dflt);
}

export function PromisedAnswer_getTransform(ptr: Ptr): Ptr {
  return ptr.getP(0);
}

export function PromisedAnswer_getTransformLen(ptr: Ptr): number {
  return ptr.getP(0).listLen();
}

export function PromisedAnswer_getTransformAt(ptr: Ptr, index: number): Ptr {
  return ptr.getP(0).listGetP(index);
}

/** Struct rpc.capnp:PromisedAnswer.Op. */
export const PROMISED_ANSWER_OP_DWORDS = 1;
export const PROMISED_ANSWER_OP_PWORDS = 0;
export const PromisedAnswer_Op_dataWordCount = 1;
export const PromisedAnswer_Op_pointerCount = 0;
/** Union discriminant byte offset (u16). */
export const PromisedAnswer_Op_discriminantOffset = 0;
export function PromisedAnswer_Op_which(ptr: Ptr): number {
  return ptr.getU16(0);
}
export const PromisedAnswer_Op = {
  noop: 0,
  getPointerField: 1,
} as const;
export type PromisedAnswer_Op = (typeof PromisedAnswer_Op)[keyof typeof PromisedAnswer_Op];

export function PromisedAnswer_Op_getGetPointerField(ptr: Ptr, dflt = 0): number {
  return ptr.getU16(2, dflt);
}

/** Struct rpc.capnp:CapDescriptor. */
export const CAP_DESCRIPTOR_DWORDS = 1;
export const CAP_DESCRIPTOR_PWORDS = 1;
export const CapDescriptor_dataWordCount = 1;
export const CapDescriptor_pointerCount = 1;
/** Union discriminant byte offset (u16). */
export const CapDescriptor_discriminantOffset = 0;
export function CapDescriptor_which(ptr: Ptr): number {
  return ptr.getU16(0);
}
export const CapDescriptor = {
  none: 0,
  senderHosted: 1,
  senderPromise: 2,
  receiverHosted: 3,
  receiverAnswer: 4,
  thirdPartyHosted: 5,
} as const;
export type CapDescriptor = (typeof CapDescriptor)[keyof typeof CapDescriptor];

export function CapDescriptor_getSenderHosted(ptr: Ptr, dflt = 0): number {
  return ptr.getU32(4, dflt);
}

export function CapDescriptor_getSenderPromise(ptr: Ptr, dflt = 0): number {
  return ptr.getU32(4, dflt);
}

export function CapDescriptor_getReceiverHosted(ptr: Ptr, dflt = 0): number {
  return ptr.getU32(4, dflt);
}

export function CapDescriptor_getReceiverAnswer(ptr: Ptr): Ptr {
  return ptr.getP(0);
}

export function CapDescriptor_getThirdPartyHosted(ptr: Ptr): Ptr {
  return ptr.getP(0);
}

export function CapDescriptor_getAttachedFd(ptr: Ptr, dflt = 255): number {
  return ptr.getU8(2, dflt);
}

/** Struct rpc.capnp:ThirdPartyCapDescriptor. */
export const THIRD_PARTY_CAP_DESCRIPTOR_DWORDS = 1;
export const THIRD_PARTY_CAP_DESCRIPTOR_PWORDS = 1;
export const ThirdPartyCapDescriptor_dataWordCount = 1;
export const ThirdPartyCapDescriptor_pointerCount = 1;

export function ThirdPartyCapDescriptor_getId(ptr: Ptr): Ptr {
  return ptr.getP(0);
}

export function ThirdPartyCapDescriptor_getVineId(ptr: Ptr, dflt = 0): number {
  return ptr.getU32(0, dflt);
}

/** Struct rpc.capnp:Disembargo.context (group / union overlay). */
export const DISEMBARGO_CONTEXT_DWORDS = 1;
export const DISEMBARGO_CONTEXT_PWORDS = 1;
export const Disembargo_context_dataWordCount = 1;
export const Disembargo_context_pointerCount = 1;
/** Union discriminant byte offset (u16). */
export const Disembargo_context_discriminantOffset = 4;
export function Disembargo_context_which(ptr: Ptr): number {
  return ptr.getU16(4);
}
export const Disembargo_context = {
  senderLoopback: 0,
  receiverLoopback: 1,
  accept: 2,
  provide: 3,
} as const;
export type Disembargo_context = (typeof Disembargo_context)[keyof typeof Disembargo_context];

export function Disembargo_context_getSenderLoopback(ptr: Ptr, dflt = 0): number {
  return ptr.getU32(0, dflt);
}

export function Disembargo_context_getReceiverLoopback(ptr: Ptr, dflt = 0): number {
  return ptr.getU32(0, dflt);
}

export function Disembargo_context_getProvide(ptr: Ptr, dflt = 0): number {
  return ptr.getU32(0, dflt);
}
