/**
 * v1 emit skeleton for capnpc-ts.
 *
 * Full struct/enum/union emit is TODO (capnp-ts-mga5). This path writes a
 * TypeScript module whose header comment records CGR node / requestedFiles
 * counts so the plugin pipeline can be smoke-tested before the full emitter.
 */

import type { CgrSummary } from "./cgr-walk.ts";
import { basename, dirname, join } from "node:path";
import { mkdirSync, writeFileSync } from "node:fs";

export type EmitResult = {
  /** Paths written (absolute or cwd-relative as given to writeFileSync). */
  written: string[];
  /** Generated source when no file path was resolved (stdout fallback). */
  stdoutFallback?: string;
};

/** Map schema path `foo/bar.capnp` -> `bar.ts` (cwd of the plugin process). */
export function outputNameForSchema(schemaPath: string): string {
  const base = basename(schemaPath);
  const stem = base.endsWith(".capnp") ? base.slice(0, -".capnp".length) : base;
  return `${stem}.ts`;
}

/**
 * Emit one stub TypeScript module for a requested schema file.
 * Content is intentionally minimal: counts + TODO markers for full emit.
 */
export function emitStubModule(
  summary: CgrSummary,
  schemaPath: string,
): string {
  const out = outputNameForSchema(schemaPath);
  const lines = [
    `/**`,
    ` * Generated by @haozeke/capnpc-ts (skeleton). Do not hand-edit long-term.`,
    ` *`,
    ` * Source schema: ${schemaPath}`,
    ` * CodeGeneratorRequest: nodes=${summary.nodeCount}, requestedFiles=${summary.requestedFileCount}`,
    ` *`,
    ` * TODO: full two-pass emit - structs, enums as const maps,`,
    ` * unions/which, List(Text) helpers, u64 via get-u64 (not u32).`,
    ` * Interim hand-rolled AddressBook lives at`,
    ` * packages/runtime/src/generated/addressbook.ts until this emitter lands.`,
    ` */`,
    ``,
    `// Output target: ${out}`,
    `export const __capnpcTsSkeleton = {`,
    `  schemaPath: ${JSON.stringify(schemaPath)},`,
    `  nodeCount: ${summary.nodeCount},`,
    `  requestedFileCount: ${summary.requestedFileCount},`,
    `} as const;`,
    ``,
  ];
  return lines.join("\n");
}

/**
 * Write stub modules for each requested file under `outDir` (default cwd).
 * If the CGR listed no filenames, write `codegen-request.ts` with counts only.
 */
export function emitFromSummary(
  summary: CgrSummary,
  outDir: string = process.cwd(),
): EmitResult {
  const written: string[] = [];
  const paths =
    summary.requestedFilenames.length > 0
      ? summary.requestedFilenames
      : ["codegen-request.capnp"];

  for (const schemaPath of paths) {
    const name = outputNameForSchema(schemaPath || "codegen-request.capnp");
    const dest = join(outDir, name);
    const src = emitStubModule(summary, schemaPath || "(unknown)");
    mkdirSync(dirname(dest), { recursive: true });
    writeFileSync(dest, src, "utf8");
    written.push(dest);
  }

  return { written };
}

/**
 * Single-module string emit (tests / dry-run). Prefers first requested filename.
 */
export function emitSourceString(summary: CgrSummary): string {
  const schemaPath =
    summary.requestedFilenames[0] ?? "codegen-request.capnp";
  return emitStubModule(summary, schemaPath);
}
