/**
 * @haozeke/capnp — pure TypeScript Cap'n Proto wire runtime.
 */

export {
  ErrorCode,
  CapnpError,
  WireKind,
  PtrKind,
  ListElementSize,
  CAPNP_WORD_BYTES,
  DEFAULT_TRAVERSAL_WORDS,
  DEFAULT_DEPTH_LIMIT,
  MAX_SEGMENTS,
  listStepBits,
} from "./kinds.ts";
export type {
  ErrorCodeName,
  WireKindCode,
  PtrKindCode,
  ListElementSizeCode,
} from "./kinds.ts";

export {
  loadU8,
  storeU8,
  loadU16,
  storeU16,
  loadU32,
  storeU32,
  loadU64,
  storeU64,
  loadI8,
  storeI8,
  loadI16,
  storeI16,
  loadI32,
  storeI32,
  loadI64,
  storeI64,
  loadF32,
  storeF32,
  loadF64,
  storeF64,
} from "./endian.ts";

export {
  kindOf,
  offsetOf,
  structDataWords,
  structPointerWords,
  listElementSize,
  listElementCount,
  farIsDouble,
  farPadOffset,
  farSegmentId,
  capIndex,
  makeStruct,
  makeList,
  makeFar,
  makeCap,
  wp_kind,
  wp_offset,
  wp_struct_dwords,
  wp_struct_pwords,
  wp_list_esize,
  wp_list_count,
  wp_far_two,
  wp_far_off,
  wp_far_seg,
  wp_cap_index,
  wp_make_struct,
  wp_make_list,
  wp_make_far,
  wp_make_cap,
} from "./pointer.ts";
