/**
 * Self-host smoke: framed CodeGeneratorRequest fixtures (from capnp-fortran
 * test/fixtures/*.cgr.bin, same bytes as `capnp compile -o-`) must open
 * without crashing and emit a non-empty TypeScript stub, including large
 * CGRs (schema.capnp self-schema, rpc).
 */
import { describe, expect, test } from "bun:test";
import { readdirSync, readFileSync, statSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import {
  emitSourceString,
  parseFramedSegments,
  summarizeCgr,
  summarizeViaHandWalk,
} from "../src/index.ts";

const here = dirname(fileURLToPath(import.meta.url));
const fixturesDir = join(here, "fixtures");

function listCgrFixtures(): string[] {
  return readdirSync(fixturesDir)
    .filter((n) => n.endsWith(".cgr.bin"))
    .sort();
}

function loadFixture(name: string): Uint8Array {
  return new Uint8Array(readFileSync(join(fixturesDir, name)));
}

describe("CGR fixture smoke", () => {
  const names = listCgrFixtures();

  test("fixtures directory has copied .cgr.bin files", () => {
    expect(names.length).toBeGreaterThanOrEqual(1);
    expect(names).toContain("schema.cgr.bin");
    expect(names).toContain("addressbook.cgr.bin");
  });

  test.each(names)("summarize + emit does not crash: %s", async (name) => {
    const bytes = loadFixture(name);
    expect(bytes.length).toBeGreaterThan(0);

    const segs = parseFramedSegments(bytes);
    expect(segs.length).toBeGreaterThanOrEqual(1);

    const summary = await summarizeCgr(bytes);
    expect(summary.nodeCount).toBeGreaterThan(0);
    expect(summary.requestedFileCount).toBeGreaterThan(0);
    expect(summary.requestedFilenames.length).toBe(summary.requestedFileCount);

    const src = emitSourceString(summary);
    expect(src.length).toBeGreaterThan(0);
    expect(src).toContain("__capnpcTsSkeleton");
    expect(src).toContain(`nodeCount: ${summary.nodeCount}`);
    expect(src).toContain("Generated by @haozeke/capnpc-ts");
  });

  test("large schema.cgr.bin (schema.capnp self) emits non-empty stub", async () => {
    const bytes = loadFixture("schema.cgr.bin");
    // Self-schema CGR is tens of KiB; catch truncated copies early.
    expect(bytes.length).toBeGreaterThan(10_000);

    const summary = await summarizeCgr(bytes);
    expect(summary.nodeCount).toBeGreaterThan(20);
    expect(summary.requestedFileCount).toBe(1);
    // Filename may be basename or path depending on how the fixture was built.
    expect(summary.requestedFilenames[0] ?? "").toMatch(/schema\.capnp$/);

    const src = emitSourceString(summary);
    expect(src.length).toBeGreaterThan(100);
    expect(src).toContain("nodes=");
    expect(src).toMatch(/nodeCount:\s*\d+/);
  });

  test("large rpc.cgr.bin emits non-empty stub with multi-file request", async () => {
    const bytes = loadFixture("rpc.cgr.bin");
    expect(bytes.length).toBeGreaterThan(10_000);

    const summary = await summarizeCgr(bytes);
    expect(summary.nodeCount).toBeGreaterThan(10);
    expect(summary.requestedFileCount).toBeGreaterThanOrEqual(1);

    const src = emitSourceString(summary);
    expect(src.length).toBeGreaterThan(100);
    expect(src).toContain("__capnpcTsSkeleton");
  });

  test("Message path and hand walk agree on single-segment addressbook.cgr.bin", async () => {
    // Hand walk is near-pointer / single-segment only. Large multi-segment
    // CGRs (schema, rpc) rely on Message.fromFlat; both paths must agree
    // where hand walk applies.
    const bytes = loadFixture("addressbook.cgr.bin");
    expect(parseFramedSegments(bytes).length).toBe(1);
    const viaMessage = await summarizeCgr(bytes);
    const viaHand = summarizeViaHandWalk(bytes);
    expect(viaHand.nodeCount).toBe(viaMessage.nodeCount);
    expect(viaHand.requestedFileCount).toBe(viaMessage.requestedFileCount);
    expect(viaHand.requestedFilenames).toEqual(viaMessage.requestedFilenames);
  });

  test("multi-segment large CGR still opens via Message (hand walk may not)", async () => {
    for (const name of ["schema.cgr.bin", "rpc.cgr.bin"] as const) {
      const bytes = loadFixture(name);
      expect(parseFramedSegments(bytes).length).toBeGreaterThan(1);
      const summary = await summarizeCgr(bytes);
      expect(summary.nodeCount).toBeGreaterThan(0);
      const src = emitSourceString(summary);
      expect(src).toContain("__capnpcTsSkeleton");
    }
  });

  test("capnpc-ts CLI --stdout on schema.cgr.bin exits 0 and emits", async () => {
    const fixture = join(fixturesDir, "schema.cgr.bin");
    const bin = join(here, "..", "bin", "capnpc-ts");
    const proc = Bun.spawn([bin, "--stdout", fixture], {
      stdout: "pipe",
      stderr: "pipe",
    });
    const [stdout, stderr, exitCode] = await Promise.all([
      new Response(proc.stdout).text(),
      new Response(proc.stderr).text(),
      proc.exited,
    ]);
    expect(exitCode).toBe(0);
    expect(stderr).toContain("CGR ok");
    expect(stdout).toContain("__capnpcTsSkeleton");
    expect(stdout.length).toBeGreaterThan(100);
    // Large fixture: binary on disk is large; emit is still a skeleton stub.
    expect(statSync(fixture).size).toBeGreaterThan(10_000);
  });
});
