/**
 * Generated by @haozeke/capnpc-ts. Do not hand-edit.
 *
 * Source schema: adder.capnp
 * CodeGeneratorRequest: nodes=4, requestedFiles=1
 * File id: 0xbf5e831ac9f0d2a1 (emitted 1 nested nodes)
 *
 * Enums are const maps (Bun strip-safe). UInt64/Int64 use getU64/bigint.
 */

import type { Ptr, StructBuilder } from "@haozeke/capnp";

export const __capnpcTsMeta = {
  schemaPath: "adder.capnp",
  nodeCount: 4,
  requestedFileCount: 1,
  fileId: 0xbf5e831ac9f0d2a1n,
  emittedNodes: 1,
} as const;

/** Interface adder.capnp:Adder. */
export const ADDER_INTERFACE_ID = 0xea01e10cbc414411n;

export const Adder_methods = {
  add: { ordinal: 0, paramsDwords: 2, paramsPwords: 0, resultsDwords: 1, resultsPwords: 0 },
} as const;

/** Calls Adder methods on an imported capability. */
export class AdderClient {
  constructor(
    private readonly conn: {
      sendCall(
        importedCapId: number,
        interfaceId: bigint,
        methodId: number,
        fillParams?: (params: StructBuilder) => void,
        paramsDwords?: number,
        paramsPwords?: number,
      ): number;
    },
    private readonly importedCapId: number,
  ) {}

  /** Send Adder.add; returns the questionId. */
  add(fillParams?: (params: StructBuilder) => void): number {
    const m = Adder_methods.add;
    return this.conn.sendCall(
      this.importedCapId,
      ADDER_INTERFACE_ID,
      m.ordinal,
      fillParams,
      m.paramsDwords,
      m.paramsPwords,
    );
  }

}

/** Implement Adder by extending this and overriding its methods. */
export abstract class AdderServer {
  abstract add(params: Ptr, results: StructBuilder): void;

  /** Route one Call. Throws when the id or ordinal is not ours. */
  dispatch(
    interfaceId: bigint,
    methodId: number,
    params: Ptr,
    results: StructBuilder,
  ): void {
    if (interfaceId !== ADDER_INTERFACE_ID) {
      throw new Error(`Adder: wrong interface ${interfaceId}`);
    }
    switch (methodId) {
      case 0:
        this.add(params, results);
        return;
      default:
        throw new Error(`Adder: no method ${methodId}`);
    }
  }
}
